#!/usr/bin/env bash
set -euo pipefail
if ! command -v asdf &>/dev/null; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
  . ~/.asdf/asdf.sh
fi
asdf plugin add protonge https://github.com/GloriousEggroll/proton-ge-custom.git || true
asdf install protonge latest
echo "Proton GE Installed"
